### ISSUE TITLE
Add calendário

### ISSUE THREAD

**Issue by bralmoretti** [dceusp/dceusp.github.io#2]
Adicionar calendário na página inicial.

Avaliar possibilidade de importar arquivo do ICS para preencher o calendário.

**Comment by bralmoretti** [comment]
O calendário foi feito e está na página inicial, porém precisa tirar os eventos do arquivo 'calendar.js' e colocar em outro documento para melhor manutenção futura.

**Comment by Potalej** [comment]
Issue resolvida no commit 332d1d7.
